#Read and Show Image

In [ ]:
# Read Image, print shape, apply color map, and display image.

import cv2

img1=cv2.imread('files/1.jpg') # read the image
img2=cv2.imread('files/1.jpg',0) # read the image
img3=cv2.imread('files/1.jpg',-1) # read the image
cimg=cv2.applyColorMap(img3,0)
print(img1.shape) #print size of the image height=360 width=540 color channel=3 (RGB)
print(img2.shape) #print size of the image height=408 width=612 color channel=3 (RGB)
print(img1) #print the color of image  in array form
print(img2) #print the color of image  in array form
cv2.imshow('image1',img1) # display the image
cv2.imshow('image2',img2) # display the image
cv2.imshow('image3',img3) # display the image
cv2.imshow('cimg',cimg) # display the image
cv2.waitKey(0) # # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows() # close all windows
# cv2.destroyWindow('image1')


(360, 540, 3)
(360, 540)
[[[218 196 118]
  [219 197 119]
  [220 198 120]
  ...
  [240 226 177]
  [240 226 177]
  [240 226 177]]

 [[218 196 118]
  [219 197 119]
  [220 198 120]
  ...
  [240 226 177]
  [240 226 177]
  [240 226 177]]

 [[219 197 119]
  [219 197 119]
  [220 198 120]
  ...
  [241 227 178]
  [241 227 178]
  [241 227 178]]

 ...

 [[181 153  42]
  [181 153  42]
  [181 153  42]
  ...
  [221 201 114]
  [221 201 114]
  [221 201 114]]

 [[181 153  42]
  [181 153  42]
  [181 153  42]
  ...
  [220 200 113]
  [220 200 113]
  [220 200 113]]

 [[180 152  41]
  [180 152  41]
  [181 153  42]
  ...
  [219 199 112]
  [219 199 112]
  [219 199 112]]]
[[175 176 177 ... 213 213 213]
 [175 176 177 ... 213 213 213]
 [176 176 177 ... 214 214 214]
 ...
 [123 123 123 ... 177 177 177]
 [123 123 123 ... 176 176 176]
 [122 122 123 ... 175 175 175]]


In [ ]:
#Display images with combined(Horizontally or vertically)

import cv2
import numpy as np

img1=cv2.imread('files/1.jpg') # read the image
img2=cv2.imread('files/2.jpg') # read the image
re_img1=cv2.resize(img1,(700,500)) # resize the image w=700 h=500
re_img2=cv2.resize(img2,(700,500)) # resize the image w=700 h=500
horizontal_image=np.hstack((re_img1,re_img2))
verticale_image=np.vstack((re_img1,re_img2))
cv2.imshow('img1',img1) # display combined image horizontally
cv2.imshow('img2',img2) # display combined image horizontally
cv2.imshow('horizontal_image',horizontal_image) # display combined image horizontally
cv2.imshow('verticale_image',verticale_image) #  display combined image vertically
cv2.waitKey(1000) # # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows() # close all windows
# cv2.destroyWindow('image1')


In [ ]:
#Image slide show

import cv2
import os

image_list=os.listdir('files')
print(image_list)
for img in image_list:
    path='files/'
    image=cv2.imread(path+img)
    cv2.imshow(img,image)
    cv2.waitKey(1000) # # image frame wait time - ms and 0 pass keyboard any key press
    cv2.destroyAllWindows() # close all windows 

['1.jpg', '2.jpg']


In [ ]:
#Draw Line in image:
    # LineType :
    # FILLED
    # LINE 4 4
    # LINE 8 8
    # LINE-AA 16


import cv2
import numpy as np

img1=cv2.imread('files/1.jpg') # read the image
linedImage=cv2.line(img=img1,pt1=(240,100),pt2=(310,100),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow('linedImage',linedImage) #  display combined image vertically
cv2.waitKey(0) # # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows() # close all windows
# cv2.destroyWindow('image1')

In [3]:
# Draw rectangle in image


import cv2
import numpy as np

img1=cv2.imread('files/1.jpg') # read the image
linedImage=cv2.rectangle(img=img1,pt1=(240,50),pt2=(310,140),color=(0,255,0),thickness=4,lineType=4)
textedImage=cv2.putText( img=linedImage,text='Face',org=(240,45),fontFace=2,fontScale=1,color=(0,0,255),thickness=1,lineType=16,bottomLeftOrigin=False)
cv2.imshow('linedImage',linedImage) #  display combined image vertically
cv2.waitKey(0) # # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows() # close all windows
# cv2.destroyWindow('image1')

In [24]:


# Draw cirle & ellipse in image
import cv2
import numpy as np

img1=cv2.imread('files/1.jpg') # read the image
cirledImage=cv2.circle(img=img1,center=(270,85), radius=50,color=(0,255,0),thickness=4,lineType=4)
ellipseImage= cv2.ellipse(img=img1, center=(270,85), axes=(50,70), angle=30, startAngle=0, endAngle=360, color=(0,255,0), thickness=-1, lineType=16)
textedImage=cv2.putText( img=cirledImage,text='Face',org=(240,45),fontFace=2,fontScale=1,color=(0,0,255),thickness=1,lineType=16,bottomLeftOrigin=False)
cv2.imshow('cirledImage',cirledImage) #  display combined image vertically
cv2.waitKey(0) # # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows() # close all windows
# cv2.destroyWindow('image1')

In [1]:


# Draw polygon in image
import cv2
import numpy as np

img1=cv2.imread('files/1.jpg') # read the image

polyImage=cv2.polylines(
    img=img1, 
    pts=[np.array([[25, 70], [25, 160],[110, 200], [200, 160],[200, 70], [110, 20]])], 
    isClosed=True,
    color=(0,255,0), 
    thickness=4,
    lineType=16
    )
cv2.imshow('polyImage',polyImage) #  display combined image vertically
cv2.waitKey(0) # # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows() # close all windows
# cv2.destroyWindow('image1')